// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	dvd "github.com/ngray1747/dvd-rental/dvd"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Store provides a mock function with given fields: _a0
func (_m *Repository) Store(_a0 *dvd.DVD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dvd.DVD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: id, status
func (_m *Repository) Update(id string, status dvd.Status) error {
	ret := _m.Called(id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, dvd.Status) error); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
