services:
- name: customer
  database:
    dbName: dvd_rental_customer
    timeout: 10
  cache:
    cacheKey: customers
- name: dvd
  database:
    dbName: dvd_rental_dvd
    timeout: 10
  cache:
    cacheKey: dvds